const menuData = [
  {
    id: 1,
    title: "1-on-1 discussion",
    category: "starter",
    fileFormat: "Phone",
    desc: `This would be a discussion to help me get an understanding of what your brand is about and how I should design for you`,
  },
  {
    id: 2,
    title: "Instagram Post Templates",
    category: "advanced",
    fileFormat: "PSD",
    desc: `Personalized, custom Instagram post templates to ensure cohesiveness between posts and help stand out from other brands`,
  },
  {
    id: 3,
    title: "Packaging Moc Ups",
    category: "special",
    price: 25,
    desc: `Realistic moc up of you packaging to captivate your customer for the whole purchasing journey`,
  },
  {
    id: 4,
    title: "Primary Logo",
    category: "starter",
    fileFormat: "SVG",
    desc: `This Logo would be Main logo depending on your brand could be the mascot logo or a type logo`,
  },
  {
    id: 5,
    title: "Instagram Highlight Icons",
    category: "advanced",
    fileFormat: "PNG",
    desc: `Custom highlight to draw attention to your best Instagram Story content and to ensure cohesiveness`
  },
  {
    id: 6,
    title: "Business Card Design",
    category: "special",
    price: 25,
    desc: `Personalized buisiness card design to give to clients and potential partners for a professional`,
  },
  {
    id: 7,
    title: "Custom Colour Palette",
    category: "starter",
    fileFormat: "PDF",
    desc: `A collection of 3-5 colours that would build the base of the brand identity with a explanation of the uses for each colour `,
  },
  {
    id: 8,
    title: "Pintrest Ad Template",
    category: "advanced",
    fileFormat: "JPEG",
    desc: `Engaging ad post to help attract customers to you page great scaled for both Pintrest and Instagram Stories`,
  },
  {
    id: 9,
    title: "NFC Stickers",
    category: "special",
    price: 50,
    desc: `NFC Sticker programmed to make it easy to share your socials and website to whoever you come by and make great additions to throw into packages. Each order comes with 50 units`,
  },
  {
    id: 10,
    title: "Typography",
    category: "starter",
    fileFormat: "PDF",
    desc: `Font pairs and collection both for post and website uses, as well as a type logo that can be used in different packaging and branding situations `,
  },
  {
    id: 11,
    title: "2 Ammends",
    category: "starter",
    fileFormat: "Phone",
    desc: `This is the chance to tweak or change the direction of the brand design if anything was missed the first time`,
  },
  {
    id: 12,
    title: "Monogram Logos",
    category: "starter",
    fileFormat: "SVG",
    desc: `Logo that would be used for monogram prints perfect for packaging and any type of patterned print for posts `,
  },
  {
    id: 13,
    title: "Final Logo Files",
    category: "starter",
    fileFormat: "SVG,  PNG",
    desc: `Access to svg of all logo and type logos and a pdf docuement putting all the assets in a organized format`,
  },
  {
    id: 14,
    title: "Brand Pattern",
    category: "advanced",
    fileFormat: "SVG",
    desc: `Brand Patterns to help give texture and depth to brand design great for post background and packaging `,
  },
  {
    id: 15,
    title: "1 Special Menu Item",
    category: "advanced",
    fileFormat: "",
    desc: `Your choice of one of the services offered in the special menu price included in the package`,
  },
];

export default menuData;
